-- Vault of Archavon, Trial of the Crusader, Onyxia's Lair
local WM = WrathMentor

WM:AddRaid("voa", "Vault of Archavon", { "Vault of Archavon" }, {
    {
        name = "Archavon the Stone Watcher",
        tldr = "Spread out for Rock Shards, step out of the Choking Cloud trail after Crushing Leap, and have the off-tank ready to pick him up when Stomp throws the main tank. Enrage after 5 minutes.",
        start = {
            "Main tank pulls Archavon and faces him away from the raid. An off-tank stands ready close by.",
            "Raid spreads out before the pull.",
        },
        general = {
            "Rock Shards: he throws shards at a player - stay spread out so nobody else is hit.",
            "Crushing Leap: he leaps to a random player and leaves a Choking Cloud trail. Move out of the trail.",
            "Stomp: he picks up the main tank, removes ALL threat, damages them for 8 seconds, then throws them across the room. The off-tank must pick him up immediately.",
            "Enrage after 5 minutes wipes the raid, so this is a DPS check.",
        },
        tank = { "Main tank: after being thrown, run back to the group. Off-tank: pick him up the moment Stomp begins." },
        heal = { "Heal the main tank through the 8-second Stomp and the raid through Rock Shards." },
        dps = { "Stay spread for Rock Shards; leave the Choking Cloud; keep DPS high for the 5-minute enrage." },
        abilities = {
            { id = 58678, name = "Rock Shards", desc = "Shards thrown at a player that hit those close to them. Stay spread." },
            { id = 60894, name = "Crushing Leap", desc = "He leaps to a random player; it leaves a trail behind." },
            { id = 58965, name = "Choking Cloud", desc = "The poison trail left by Crushing Leap. Move out." },
            { id = 60880, name = "Stomp", desc = "Picks up the main tank, removes all threat, damages then throws them. Off-tank takes over." },
        },
    },
    {
        name = "Emalon the Storm Watcher",
        aliases = { "Tempest Minion" },
        tldr = "Melee run out for Lightning Nova, everyone spread for Chain Lightning, and every 45 seconds ALL DPS switch to the Tempest Minion that got Overcharge and kill it before 10 stacks (it explodes for raid-wipe damage).",
        start = {
            "Emalon starts with 4 Tempest Minions. The OFF-TANK pulls first and grabs the minions and Emalon, moving to one side of the room.",
            "The main tank then takes Emalon from the off-tank and drags him to the opposite side - keep Emalon and the minions AWAY from each other because of Lightning Nova.",
            "Do not start DPS until both tanks have their targets.",
        },
        general = {
            "Overcharge every 45 seconds: a random Tempest Minion is healed to full and gets a stacking buff (bigger and +20% damage). It gains another stack every 2 seconds. At 10 stacks it explodes (Overcharged Blast) for massive nature damage to the raid and usually wipes it. ALL DPS must swap to that Minion and kill it before it reaches 10 stacks.",
            "Lightning Nova is a long cast that hurts more the closer you are: melee run away from Emalon as soon as it starts; the off-tank stays far from the boss with the minions.",
            "Chain Lightning: stay spread out. A Nature Resistance Totem helps with Chain Lightning and Lightning Nova.",
            "When the minion dies Emalon summons a new one; the off-tank grabs it. There is a 6-minute enrage.",
        },
        tank = { "Off-tank: hold the minions far from Emalon, pick up any new one. Main tank: keep Emalon away from the minions." },
        heal = { "Bring 3-5 healers. Heal through Chain Lightning and Lightning Nova; keep tanks up." },
        dps = { "Swap immediately to the Overcharged minion and kill it before 10 stacks, then back to Emalon. Melee run out on Lightning Nova." },
        abilities = {
            { id = 64218, name = "Overcharge", desc = "A random Tempest Minion is healed and stacks a buff every 2 seconds. Kill it before 10 stacks." },
            { ids = { 65279, 64216 }, name = "Lightning Nova", desc = "A long cast; more damage the closer you are to Emalon. Run away." },
            { ids = { 64213, 64215 }, name = "Chain Lightning", desc = "Lightning that jumps between players. Stay spread." },
        },
    },
    {
        name = "Koralon the Flame Watcher",
        tldr = "Two tanks stay stacked together to split Meteor Fists, healers watch Burning Breath raid damage, everyone moves out of Flaming Cinder fire, and burn him because Burning Fury grows every 20 seconds.",
        start = {
            "Tank Koralon away from fire patches and turn him away from the raid so melee can engage.",
            "Have an off-tank stand right next to the main tank for Meteor Fists. Bring a Fire Resistance Aura (Paladin) or Totem (Shaman) - all his damage is fire.",
        },
        general = {
            "Burning Fury: every 20 seconds he gains a stacking damage buff (a soft enrage). Kill him quickly.",
            "Meteor Fists hits the tank and splits damage with other targets: keep the off-tank next to the main tank (or alternate raid cooldowns on the main tank if solo tanking).",
            "Burning Breath: raid-wide damage - healers watch for it.",
            "Flaming Cinder: flame patches on the ground - move out of them.",
        },
        tank = { "Stack the two tanks together for Meteor Fists. Face him away and keep him out of fire." },
        heal = { "Heal Burning Breath and Meteor Fists. Fire Resistance helps." },
        dps = { "Melee stay stacked in front only as instructed; move out of Flaming Cinder. Use cooldowns - Burning Fury keeps growing." },
        abilities = {
            { ids = { 66725, 68161 }, name = "Meteor Fists", desc = "Hits the tank in front of him and splits damage with others near the target." },
            { ids = { 66665, 68160 }, name = "Burning Breath", desc = "Raid-wide fire damage. Heal through it." },
            { ids = { 66681, 66684 }, name = "Flaming Cinder", desc = "Fire patches on the ground. Move out." },
            { id = 66721, name = "Burning Fury", desc = "A stacking damage buff every 20 seconds (soft enrage)." },
        },
    },
    {
        name = "Toravon the Ice Watcher",
        tldr = "Kill the Frozen Orbs, heal everyone up before Whiteout (about every 40 seconds), taunt-swap on Frostbite stacks, and stay out of Freezing Ground.",
        start = {
            "Two tanks so they can taunt off each other. Healers spread out among the raid.",
        },
        general = {
            "Frozen Orbs appear: kill them.",
            "Whiteout about every 40 seconds increases the Frost damage everyone takes for the rest of the fight. Healers make sure everyone is healthy before it is cast.",
            "Tanks taunt off each other to deal with stacks of Frostbite.",
            "Freezing Ground is cast throughout the fight: stay out of it.",
        },
        tank = { "Taunt off each other on Frostbite stacks." },
        heal = { "Top everyone off before each Whiteout; Frost damage taken keeps increasing." },
        dps = { "Kill Frozen Orbs first; stay out of Freezing Ground." },
        abilities = {
            { id = 72034, name = "Whiteout", desc = "Big frost damage that also raises the frost damage you take. Heal up beforehand." },
            { id = 72090, name = "Freezing Ground", desc = "Frozen ground effects. Don't stand in them." },
        },
    },
}, "wowtbc.gg (Vault of Archavon boss guide), Warcraft Tavern (Emalon 10/25), Ten Ton Hammer (Emalon), Almar's Guides (Koralon); Syndicate Guild not checked for this raid")

WM:AddRaid("toc", "Trial of the Crusader", { "Trial of the Crusader" }, {
    {
        name = "Northrend Beasts",
        aliases = { "Gormok the Impaler", "Acidmaw", "Dreadscale", "Icehowl" },
        tldr = "Three beasts in a row: Gormok (casters stay 15 yards away, kill Snobolds), the worms Acidmaw and Dreadscale (opposite debuffs cancel each other), then Icehowl (dodge the charge).",
        start = {
            "Gormok comes first, then the two worms together, then Icehowl. Assign tanks: two on Gormok (Impale swap), one per worm, then two on Icehowl.",
            "Everyone knows which worm is mobile: DREADSCALE starts MOBILE, ACIDMAW starts STATIONARY. They swap after burrowing.",
        },
        general = {
            "## Gormok the Impaler",
            "Casters stay at least 15 yards from him to avoid Staggering Stomp. Tanks taunt off each other for Impale.",
            "Snobold Vassals spawn each time he loses 20% health, on a random player - ranged bring them to melee and kill them. Avoid Fire Bomb from the Snobolds.",
            "## Acidmaw and Dreadscale",
            "One worm is mobile, the other stationary; they switch after burrowing. The mobile worm only applies its debuff to its tank - tanks must kite the mobile one. The stationary worm puts its debuff on a random group of players.",
            "Their debuffs cancel each other: if you get Paralytic Toxin from Acidmaw, run to the tank of Dreadscale (they have Burning Bile) to remove it. If Dreadscale is mobile and you're hit by Burning Bile, run to the tank on Acidmaw to remove the Paralytic Toxin.",
            "Stay spread but not too far from Dreadscale, so the Paralytic Toxin doesn't freeze you. Kill Acidmaw first and don't stand in front of the worms.",
            "## Icehowl",
            "Melee stand at max melee range to avoid Whirl. Spread for Arctic Breath. Healers watch tank spikes from Ferocious Butt and top everyone off after Arctic Breath so nobody dies to Massive Crash. If Icehowl charges you, get out of the way.",
        },
        tank = {
            "Gormok: taunt-swap on Impale. Worms: kite the mobile worm. Icehowl: prepare for Ferocious Butt.",
        },
        heal = { "Heal Impale on Gormok; dispel/heal the worm debuffs; top everyone off after Arctic Breath." },
        dps = { "Kill Snobolds; then Acidmaw first; avoid Icehowl's charge and stay at max melee range for Whirl." },
        abilities = {
            { id = 67648, name = "Staggering Stomp", desc = "Gormok's stomp: interrupts casters within 15 yards for 8 seconds." },
            { id = 67477, name = "Impale", desc = "Bleeding stacking strike on Gormok's tank. Swap." },
            { id = 66823, name = "Paralytic Toxin", desc = "Acidmaw's paralysing debuff. Cancelled by Burning Bile." },
            { id = 66869, name = "Burning Bile", desc = "Dreadscale's fire debuff. Cancelled by Paralytic Toxin." },
            { id = 66770, name = "Ferocious Butt", desc = "Icehowl's tank hit." },
            { id = 67345, name = "Whirl", desc = "Icehowl's melee whirl. Melee stay at max range." },
            { id = 66689, name = "Arctic Breath", desc = "Icehowl's frost breath damage. Spread." },
            { id = 66683, name = "Massive Crash", desc = "Icehowl's crash after a charge. Be healthy." },
        },
        hard = {
            "Heroic mode: each phase is on a TIMER. The next beast can spawn before the previous one dies - keep DPS high.",
            "A Paladin can use Hand of Protection to remove the Impale debuff during the phase 2 transition.",
            "Gormok's Snobold Vassals and Fire Bombs are more dangerous on heroic - kill Snobolds quickly and avoid the bombs.",
        },
    },
    {
        name = "Lord Jaraxxus",
        tldr = "Tank him in the middle and spread around him. Interrupt Fel Fireball, dispel Nether Power, heal Incinerate Flesh and run to the edge with Legion Flame. On heroic kill Nether Portals and Infernal Eruptions at once.",
        start = {
            "Tank Jaraxxus in the center of the room. Everyone spreads out around him before the pull (Fel Lightning).",
            "Assign an interrupter for Fel Fireball, dispellers (Mages can Spellsteal) for Nether Power, and healers to focus the Incinerate Flesh target.",
        },
        general = {
            "Spread out to help with Fel Lightning. Interrupt Fel Fireball. Dispel Nether Power (Mages: Spellsteal).",
            "Incinerate Flesh is a healing-absorb shield on a random player, not direct damage - spam heal through it to clear it before it expires, or it triggers Burning Inferno (raid-wide fire damage) when it runs out.",
            "If you are targeted by Legion Flame, run toward the edge of the room.",
            "Fire Resistance Aura (Paladin) helps with raid damage.",
        },
        tank = { "Hold Jaraxxus in the center." },
        heal = { "Spam heal the Incinerate Flesh target to burn through the absorb shield before it expires; watch Touch of Jaraxxus on heroic." },
        dps = { "Interrupt Fel Fireball, spread out, and kill adds when Nether Portals appear." },
        abilities = {
            { id = 66532, name = "Fel Fireball", desc = "A big fire cast. Interrupt it." },
            { id = 66528, name = "Fel Lightning", desc = "Lightning that hurts players standing near each other. Stay spread." },
            { id = 66237, name = "Incinerate Flesh", desc = "Absorbs the next chunk of healing on a random player and halves their damage done. If it isn't healed away before it expires, it explodes into Burning Inferno - raid-wide fire damage." },
            { id = 66197, name = "Legion Flame", desc = "Fire on a player that burns the ground. Run to the edge." },
            { id = 66228, name = "Nether Power", desc = "Jaraxxus' buff. Dispel or Spellsteal it." },
        },
        hard = {
            "On normal mode, Nether Portal is just a visual warning that a single Mistress of Pain is about to spawn - kill her quickly when she appears. Infernal Eruption separately summons a Volcano that spawns Infernals that charge and AoE - CC or kill them.",
            "On heroic, both the Nether Portal and the Infernal Eruption's Volcano become attackable and keep spawning adds (a Mistress of Pain and Infernals respectively) until destroyed - kill the portal/volcano itself as fast as possible instead of only the adds it drops.",
            "The Mistress of Pain gains Mistress's Kiss: if you get it, cast a spell from a non-primary school to trigger it.",
            "Jaraxxus also gains Touch of Jaraxxus: another reason to stay spread out.",
        },
    },
    {
        name = "Faction Champions",
        tldr = "A PvP-style fight against NPC champions: use crowd control everywhere, kill the healers first (Restoration Shaman, Discipline Priest), then the Rogue, then the melee. Start with a Warrior AoE fear to pop their trinkets.",
        start = {
            "If you can, start with an AoE fear from a Warrior to make the NPCs waste their trinkets.",
            "Everyone should use every crowd-control ability they have, especially early when things are hectic.",
        },
        general = {
            "The NPCs reset their aggro table throughout the fight: if you are not a tank, be ready to kite and use defensive cooldowns.",
            "Recommended kill order: Restoration Shaman, Discipline Priest, then the Rogue.",
            "After those three are dead, focus the melee NPCs and crowd control the rest.",
            "Healers watch players targeted by the Rogue.",
        },
        tank = { "Tank the melee champions and expect threat resets." },
        heal = { "Watch for the Rogue's targets; save dispels/cooldowns for burst." },
        dps = { "Follow the kill order and CC targets; kite when they reset threat." },
        abilities = {},
        hard = {
            "Heroic mode: same plan as normal; champions hit harder and last longer, so coordinated crowd control matters even more. Stay disciplined on kill order: Restoration Shaman, Discipline Priest, Rogue.",
        },
    },
    {
        name = "Twin Val'kyr",
        aliases = { "Fjola Lightbane", "Eydis Darkbane" },
        tldr = "Fjola (light) and Eydis (dark) share one health pool. Half the raid attunes to light, half to dark; soak orbs of YOUR colour only; swap colours for the matching vortex and opposite for the shields.",
        start = {
            "Split the raid into two halves: half attune to the LIGHT buff and half to the DARK buff at the start. The light half damages Eydis Darkbane; the dark half damages Fjola Lightbane.",
            "Everyone soaks the Concentrated Essence orbs that roam the room that match your attunement and avoids the other colour.",
        },
        general = {
            "Soaking enough orbs gives Empowered Light or Empowered Darkness (depending on the colour).",
            "Light Vortex / Dark Vortex: swap colours to match the boss casting it, then swap back when the cast ends.",
            "Shield of Lights / Shield of Darkness: swap to the OPPOSITE colour of the boss and break the shield so you can interrupt Twin's Pact, then switch back.",
            "When one boss casts its shield, the other gains Power of the Twins - that tank needs focus healing.",
            "Doorway strategy: assign 2-3 soakers to handle the orbs and stack the rest of the raid at the entrance.",
            "Fire Resistance Aura and Shadow Resistance Aura help mitigate raid damage.",
        },
        tank = { "Each tank holds one Val'kyr. The one that gains Power of the Twins needs extra healing." },
        heal = { "Focus the tank with Power of the Twins. Keep your attunement colour in mind." },
        dps = { "Attune, soak your colour, swap for vortexes and shields as described, and kill both close together." },
        abilities = {
            { ids = { 65875, 65876 }, name = "Twin's Pact", desc = "A big heal/buff cast by a Val'kyr. Interrupt it after breaking the shield." },
            { id = 66046, name = "Light Vortex", desc = "Fjola's vortex. Swap to light to avoid it." },
            { id = 66058, name = "Dark Vortex", desc = "Eydis' vortex. Swap to dark to avoid it." },
            { id = 65858, name = "Shield of Lights", desc = "Fjola's shield. Swap colours opposite of her to break it." },
            { id = 65874, name = "Shield of Darkness", desc = "Eydis' shield. Swap colours opposite of her to break it." },
            { id = 65950, name = "Touch of Light", desc = "Heroic: a light effect on a player." },
            { id = 66001, name = "Touch of Darkness", desc = "Heroic: a dark effect on a player." },
        },
        hard = {
            "Heroic mode: each Val'kyr gains an ability - Touch of Darkness (Eydis) and Touch of Light (Fjola). As long as your dark and light players are kept separated from each other, this is not a threat.",
            "When targeted by a Touch, switch your essence colour to the opposite temporarily to neutralise it, then switch back (it hurts nearby allies like Searing Light on XT-002).",
            "Assign a mobile healer (a Druid works well) as the ball collector to gather the dangerous concentrated essences for their side.",
            "The fight has no enrage, but if the Val'kyr keep powering up from orbs they will kill everyone.",
        },
    },
    {
        name = "Anub'arak",
        tldr = "P1: kill Frost Spheres to make Permafrost, tank Burrowers on Permafrost. P2 (burrowed): kill Scarabs and kite Pursuing Spikes onto Permafrost. P3 at 30%: Leeching Swarm - keep everyone under 50% health and use Bloodlust.",
        start = {
            "Off-tanks pick up the Nerubian Burrowers (2 in normal, 4 in heroic) and tank them near Anub'arak so they can be cleaved.",
            "Assign one DPS to kill the floating Frost Spheres so Permafrost appears on the ground.",
        },
        general = {
            "## Phase 1",
            "Frost Spheres: kill them to spawn Permafrost. On heroic you're limited to 6 Frost Spheres, on normal they respawn.",
            "Heal players with Penetrating Cold and watch tank spike damage from Freezing Slash.",
            "Tank Burrowers on top of Permafrost so they can't use Submerge. Burrowers apply Expose Weakness (heroic: also Shadow Strike - interrupt it).",
            "## Phase 2 (starts when Anub'arak burrows)",
            "Kill the Scarabs; they pursue random targets and randomly enrage (faster attacks, immune to slows and stuns).",
            "If Anub'arak Pursues you, kite the Pursuing Spikes as long as possible and then stand on Permafrost. When he reaches you he casts Impale, but it fails if he's beneath a Permafrost patch (which it consumes).",
            "## Phase 3 (below 30% health)",
            "Anub'arak uses Leeching Swarm the whole time - it leeches the target's current health every second, so healers must keep players alive WITHOUT over-healing: keep everyone under 50% health. Save Bloodlust for this phase.",
            "On heroic he keeps spawning Burrowers.",
        },
        tank = { "Tank Burrowers on Permafrost. Watch Freezing Slash stacks." },
        heal = { "Phase 3: heal without over-healing (Leeching Swarm) - keep the raid under 50% health." },
        dps = { "Kill Frost Spheres, Burrowers and Scarabs; use Permafrost to stop Pursuing Spikes; Bloodlust in phase 3." },
        abilities = {
            { id = 66012, name = "Freezing Slash", desc = "Tank hit that freezes them for 3 seconds. Heal the spike." },
            { id = 66013, name = "Penetrating Cold", desc = "A frost damage-over-time on random players (more on heroic)." },
            { id = 66118, name = "Leeching Swarm", desc = "In phase 3 he drains the raid's health and heals himself. Keep health under 50%." },
            { id = 65920, name = "Impale", desc = "He impales a player after Pursuing Spikes. Fails on Permafrost." },
            { id = 66134, name = "Shadow Strike", desc = "Heroic: Burrowers' cast. Interrupt it." },
            { id = 53421, name = "Submerge", desc = "Burrowers use this; tank them on Permafrost to stop it." },
        },
        hard = {
            "Heroic mode: 4 Nerubian Burrowers instead of 2, limited to 6 Frost Spheres, Burrowers gain Shadow Strike (interrupt it) and keep spawning in phase 3.",
            "Penetrating Cold hits more players and hits harder on heroic. A Paladin's Hand of Protection on a Pursued player makes them immune to Pursuing Spikes - use it right before a Permafrost patch, then run into the patch just before it ends to keep Permafrost available.",
        },
    },
}, "wowtbc.gg (Trial of the Grand Crusader boss guide, normal and heroic notes), Warcraft Tavern overview; Syndicate Guild not checked for this raid")

WM:AddRaid("ony", "Onyxia's Lair", { "Onyxia's Lair" }, {
    {
        name = "Onyxia",
        aliases = { "Onyxian Whelp", "Onyxian Lair Guard" },
        tldr = "P1: tank her with her back to the wall, everyone else at her sides. P2 (65%): ranged burn, AoE whelps, melee kill Lair Guards, and run out of the Deep Breath path. P3 (40%): fears and lava - keep the tank feared-free.",
        start = {
            "Tank her against a wall facing AWAY from the raid so Tail Sweep and Wing Buffet can't knock players into the whelp eggs.",
            "Everyone except the tank stands at her sides: NOT in front (Flame Breath, Wing Buffet) and NOT behind (Tail Sweep).",
            "Do not touch the whelp eggs. A Priest or Shaman must be ready to remove fear from the tank in phase 3.",
        },
        general = {
            "## Phase 1 (100% to 65%)",
            "Onyxia uses Flame Breath, Cleave, Wing Buffet and Tail Sweep. Melee stay to her sides. Tail Sweep knocks players back and into the egg cave - that spawns extra whelps.",
            "## Phase 2 (65% to 40%)",
            "She takes off and can't be hit by melee. She casts Fireball on a random target and nearby allies. Deep Breath: at random times she emotes; note her position and direction and get out of her path - it kills anything in the line.",
            "Waves of Onyxian Whelps spawn (two sets of 20 every 90 seconds at the start of the phase), and Onyxian Lair Guards (#{1/2} per cast, first after 15 seconds, then every 30 seconds) with Blast Nova and Ignite Weapon.",
            "Ranged DPS burn Onyxia down but must AoE the whelps when they come; melee focus the Lair Guards. A tank gathers whelps for AoE, with healers close by.",
            "## Phase 3 (40%)",
            "She lands and casts Bellowing Roar - a raid-wide fear for about 3 seconds followed by lava eruptions. Finish adds while the tank repositions her at the wall.",
            "Similar to phase 1, plus periodic fears, eruption damage and occasional whelps. Remove fear from the tank (Priest Fear Ward / Shaman Tremor Totem) - if a feared tank runs into the raid, her next breath can wipe you.",
        },
        tank = { "Face her away from the raid at a wall. Phase 2: gather the whelps; another tank takes the Lair Guards away from non-melee players." },
        heal = { "Phase 1: heal Flame Breath/Wing Buffet on the tank. Phase 2: stay close to the whelp tank. Phase 3: heal eruption damage." },
        dps = { "Stay at her sides in phases 1 and 3. Phase 2: ranged burn her and AoE whelps; melee kill Lair Guards. Move out of Deep Breath." },
        abilities = {
            { ids = { 68970, 18435 }, name = "Flame Breath", desc = "A frontal cone of massive fire damage. Only the tank is in front." },
            { id = 18500, name = "Wing Buffet", desc = "A frontal knockback attack." },
            { id = 68867, name = "Tail Sweep", desc = "Knocks back and damages players behind her. Can throw you into the whelp cave." },
            { ids = { 18392, 68926 }, name = "Fireball", desc = "Fire damage on a target and those near them in phase 2." },
            { ids = { 68959, 17086, 18351 }, name = "Deep Breath", desc = "She flies across the room; anything in the line dies. Move out of her path." },
            { id = 18431, name = "Bellowing Roar", desc = "A raid-wide fear. Remove fear from the tank." },
            { id = 68958, name = "Blast Nova", desc = "Onyxian Lair Guards' AoE blast." },
        },
    },
}, "Warcraft Wiki (Onyxia tactics, level 80 changes), Icy Veins, wow-anniversary.fi; Syndicate Guild not checked for this raid")
