-- Ulduar (10/25). Hard modes are explained under each boss.
local WM = WrathMentor

WM:AddRaid("uld", "Ulduar", { "Ulduar" }, {
    {
        name = "Flame Leviathan",
        aliases = { "Salvaged Chopper", "Salvaged Demolisher", "Salvaged Siege Engine", "Leviathan Defense Turret" },
        tldr = "A VEHICLE fight: everyone drives a Demolisher, Siege Engine or Chopper. Choppers drop Tar to slow the boss - any vehicle's fire attack ignites it for bonus damage. If Leviathan hunts you (Pursued), kite it through burning Tar. Towers left up before the pull are the hard mode.",
        start = {
            "Talk to the Lore Keeper of Norgannon in the middle of the room to activate the four Defense Towers and start the gauntlet. This is the same NPC for normal mode and hard mode - the towers you leave standing decide the difficulty (see Hard mode).",
            "Fight through the gauntlet of Iron Dwarves, Vrykul and constructs to reach the boss room. Interrupt Ulduar Colossus's Ground Slam with a Siege Engine's Electroshock.",
            "Liquid Pyrite tanks float in the sky during the gauntlet - gunners shoot them down and grab the crates so your Demolishers start the boss with pyrite banked.",
            "There are 5 of each vehicle (Demolisher, Siege Engine, Chopper).",
            "[10] With 10 players there's a driver for every Demolisher and Siege Engine, plus extra seats to fill as gunners or Chopper drivers.",
            "[25] With 25 players there is exactly enough for every Demolisher and Siege Engine to have a driver and a gunner, and every Chopper to have a driver.",
            "Get in a vehicle before driving in to start the pull.",
            "Gear up your driver's item level for a bigger, harder-hitting vehicle: seed the highest-item-level players into Demolishers first, then Siege Engines, then Choppers.",
        },
        general = {
            "## Roles",
            "Demolisher (driver + gunner): the main damage dealer. Driver uses Hurl Pyrite Barrel (stacks up to 10, your best damage) and Hurl Boulder as backup; gunner shoots down Pyrite crates with Anti-Air Rocket and reels them in with Grab Crate to keep the driver's pyrite stocked, and can Load into Catapult to be launched onto the boss by the driver's Throw Passenger.",
            "Siege Engine (driver + gunner): tanks hits and interrupts. Driver uses Ram for damage and Electroshock to interrupt Flame Vents; gunner uses Fire Cannon for damage, Anti-Air Rocket on Pyrite, and Shield Generator to soak heavy damage.",
            "Chopper (driver only): support. Drops Tar to slow the boss (see below), uses Speed Boost to ferry players, and Sonic Horn as a minor attack. Use First Aid Kit on a passenger you just picked up.",
            "## Tar and igniting it",
            "A Chopper's Tar pool slows anything standing in it, including Flame Leviathan - drop it in front of the boss (or in the path it's about to take) to keep it from catching the vehicle it is Pursuing.",
            "Tar can be ignited by fire damage from another vehicle - a Demolisher's Hurl Pyrite Barrel/Hurl Boulder or a Siege Engine's Fire Cannon both work. Burning Tar adds extra damage on top of the slow, so fire into Tar patches whenever you can, especially the one the boss is standing in.",
            "## Pursued and turrets",
            "Every 30 seconds Leviathan fixates on a random Demolisher or Siege Engine and chases it. The targeted driver kites it through Tar and uses their own speed ability (Steam Rush / Increased Speed) to stay ahead - Choppers should keep dropping fresh Tar in its path.",
            "Leviathan stacks Gathering Speed over time, moving faster the longer the fight runs. Destroying all four Leviathan Defense Turrets on its back triggers Overload Circuit: a 20-second stun, 50% increased damage taken, and it strips all Gathering Speed stacks.",
            "Ranged DPS Demolisher passengers should Load into Catapult so their driver can Throw Passenger them onto the boss to attack the turrets directly - melee can only reach one turret, ranged can reach all four. After the turrets are down, jump off and have a Chopper ferry you back to your Demolisher.",
            "Missile Barrage hits random vehicles for moderate damage throughout the fight - just heal/repair through it.",
        },
        tank = { "There is no traditional tank: Siege Engine drivers act as the front line and interrupt Flame Vents with Electroshock." },
        heal = { "There are no traditional heals either - keep your own vehicle topped up and use Shield Generator (Siege Engine gunner) or First Aid Kit (Chopper) on passengers." },
        dps = { "Demolishers do the heavy damage (keep 10 stacks of Hurl Pyrite Barrel up). Ignite Choppers' Tar whenever you can. Launch a Demolisher passenger to clear the turrets for Overload Circuit." },
        abilities = {
            { id = 62374, name = "Pursued", desc = "Leviathan fixates on one Demolisher or Siege Engine and chases it (changes every 30 seconds). Kite it through Tar and use your vehicle's speed ability." },
            { id = 62396, name = "Flame Vents", desc = "Fire damage every second for 10 seconds to everyone within 50 yards. Interrupt it with a Siege Engine's Electroshock." },
            { id = 62376, name = "Battering Ram", desc = "Leviathan rams its target for damage and a stacking debuff that increases their damage taken by 50% for 20 seconds. Avoided by not letting it catch you." },
            { id = 62375, name = "Gathering Speed", desc = "A stacking movement speed buff (up to +100%) that builds the longer the fight goes. Destroying all 4 turrets strips every stack." },
            { id = 62400, name = "Missile Barrage", desc = "A salvo of missiles that hits random vehicles for moderate damage." },
        },
        hard = {
            "How to activate: talk to the Lore Keeper of Norgannon as usual, then do NOT destroy some or all of the four Defense Towers in the gauntlet before pulling the boss. The towers you leave standing set the difficulty.",
            "Each tower left up multiplies Leviathan's health by 1.4 - almost quadruple health with all four left standing - and gives it one extra ability for the whole fight.",
            "Tower of Life -> Freya's Ward: Leviathan deals constant Nature damage to everyone near it, takes 10% less Fire damage, and periodically summons a Ward of Life and Writhing Lashers from green beams in each corner - assign a Siege Engine to each corner to kill these fast.",
            "Tower of Flame -> Mimiron's Inferno: Leviathan deals 50% more Fire damage, and meteors fall from the sky along a slow, visible path - just don't stand where they're heading.",
            "Tower of Frost -> Hodir's Fury: pale beams follow players and, when they stop moving, call down an icy comet that freezes the vehicle and deals damage over time. Hit a frozen vehicle with fire damage to break it free.",
            "Tower of Storms -> Thorim's Hammer: Leviathan deals 25% more Physical damage, and pillars of light appear and briefly later deal heavy damage to anything still standing in them - move out as soon as one appears.",
            "Keep Demolishers' Pyrite Barrel stacks up the whole fight (the boss has much more health), keep Tar lit, and make sure Chopper drivers never let Pursued vehicles get caught - a caught vehicle dies fast at these damage levels.",
            "Leaving more towers up drops better hard-mode loot in addition to the normal loot table; all four towers left up gives the best rewards.",
        },
    },
    {
        name = "Ignis the Furnace Master",
        aliases = { "Iron Construct" },
        tldr = "Lure each Iron Construct into the scorched ground, root it, then when it is Molten drag it into the water to make it Brittle and smash it. Stop casting for Flame Jets and heal the Slag Pot target.",
        start = {
            "Main tank pulls Ignis and turns him away from the raid. Off-tanks handle the Iron Constructs that wake up.",
            "Scorch leaves fire on the ground; know where the water pool is - that is where Constructs get shattered.",
        },
        general = {
            "## Ignis",
            "Stop casting when Ignis starts Flame Jets (it silences/interrupts casters) - or interrupt it.",
            "Healers keep the player caught by Slag Pot alive.",
            "The main tank faces Ignis away from the raid because of Scorch, then moves to a new area after each Scorch so they aren't standing in fire.",
            "Ignis deals 20% more damage for EVERY Iron Construct that is alive, so kill them promptly.",
            "## Iron Constructs",
            "Off-tanks kite a Construct into a patch of scorched ground and a player standing in the fire ROOTS it.",
            "When it turns Molten, break the root and kite it into the WATER to make it Brittle.",
            "Use a hard-hitting ability on a Brittle Construct to Shatter it.",
        },
        tank = {
            "Main tank: Ignis away from the raid; step out of Scorch fire. Off-tanks: kite Constructs onto scorched ground, then into the water.",
        },
        heal = { "Keep the Slag Pot victim alive and heal the tank through Scorch." },
        dps = {
            "Stop casting during Flame Jets. Balance Druids (Entangling Roots) and Mages (Frost Nova) are great for rooting Constructs.",
            "Shatter Brittle Constructs with a big hit.",
        },
        abilities = {
            { ids = { 62681, 63472 }, name = "Flame Jets", desc = "A cone of flame that interrupts spellcasting. Stop casting or interrupt Ignis." },
            { ids = { 62546, 63474 }, name = "Scorch", desc = "Puts fire on the ground near the tank. Move out; Constructs are kited over it." },
            { ids = { 62717, 63477 }, name = "Slag Pot", desc = "Grabs a random player and burns them. Healers keep them alive." },
            { id = 62488, name = "Activate Construct", desc = "Ignis wakes up another Iron Construct." },
            { id = 62382, name = "Brittle", desc = "A cooled Construct that shatters from one heavy hit." },
        },
    },
    {
        name = "Razorscale",
        tldr = "Phase 1: kill the Dark Rune adds until all four harpoons are ready, then click them to ground her. Burn her while grounded and never stand in front. At 50% she stays grounded: taunt-swap for Fuse Armor.",
        start = {
            "Four harpoon guns around the arena: you can't hit her until they are all ready.",
            "Tanks pick up the adds. Healers stand in the middle of the group so the tanks can grab adds easily (watch your aggro in the air phase).",
        },
        general = {
            "## Phase 1 (air phase)",
            "Kill adds until all four harpoons are ready. Kill priority: Dark Rune Watchers, then Dark Rune Guardians, then Dark Rune Sentinels.",
            "Interrupt Chain Lightning from the Dark Rune Watchers. Tank the Sentinels away from the raid (Whirlwind).",
            "Avoid the blue flames on the ground (Devouring Flame).",
            "When the harpoons are ready, click ALL FOUR to ground Razorscale. Then focus all damage on her and don't stand in front.",
            "Before she flies again (or transitions at 50%) she casts Flame Breath and Wing Buffet.",
            "## Phase 2 (below 50%)",
            "She is grounded permanently. She still casts Devouring Flame; the tank faces her away from the raid because of Flame Breath.",
            "Tanks taunt off each other to deal with Fuse Armor. She also applies a stacking debuff called Flame Buffet for the rest of the fight.",
        },
        tank = {
            "Phase 1: tank the adds (Sentinels away from the raid). Phase 2: tank Razorscale facing away; taunt-swap on Fuse Armor.",
        },
        heal = { "Stand centrally in phase 1 and watch aggro. Heal the tank through Flame Breath and Fuse Armor." },
        dps = { "Phase 1: kill adds in priority order. When grounded, all-in on Razorscale (not from the front)." },
        abilities = {
            { ids = { 64733, 63236 }, name = "Devouring Flame", desc = "Blue fire on the ground. Step out of it." },
            { ids = { 64021, 63317 }, name = "Flame Breath", desc = "Fire cone in front of her. Only the tank is in front." },
            { id = 64771, name = "Fuse Armor", desc = "Stacking armor reduction on the tank. Swap tanks." },
            { id = 64016, name = "Flame Buffet", desc = "A stacking damage debuff in phase 2." },
        },
    },
    {
        name = "XT-002 Deconstructor",
        tldr = "Move away from others when you have Searing Light or Gravity Bomb. Heal Tantrum. At 75/50/25% his Heart is exposed for 20 seconds - kill Scrapbots, tank Pummellers, and hit the Heart (double damage).",
        start = {
            "Tank XT-002 in the middle; the raid spreads out so bomb targets can walk away from everyone.",
            "Decide BEFORE the pull: do you want hard mode? Killing his Heart (in the Heart phase) activates it, so control your damage on the Heart if you don't.",
        },
        general = {
            "## Phase 1",
            "Move away from other players when you get Searing Light or Gravity Bomb.",
            "Tympanic Tantrum: big raid-wide damage once a minute. The timer resets each time the Heart is exposed (75/50/25%), so if you reach those thresholds in less than a minute you skip a Tantrum.",
            "## Phase 2 (at 75%, 50% and 25%; lasts 20 seconds)",
            "His Heart is exposed. Three add types spawn in the room corners: Scrapbots (kill them before they reach XT-002 or they heal him; can be crowd controlled), Boombots (explode at 50% health for damage to everything; use them to kill Scrapbots or damage the Heart), and Pummellers (tanks pick them up, DPS ignore them).",
            "The Heart of the Deconstructor takes DOUBLE damage - put as many DPS on it as possible.",
            "Killing the Heart activates Hard Mode.",
        },
        tank = { "Hold XT-002. In the Heart phase, pick up the Pummellers and hold them away from the raid." },
        heal = { "Heavy raid healing for Tympanic Tantrum. Raid cooldowns like Divine Guardian help." },
        dps = {
            "Bomb targets walk away from the raid. In the Heart phase go all-in on the Heart (or Scrapbots if they're about to reach XT-002).",
            "Rogues can Feint to reduce Tantrum damage.",
        },
        abilities = {
            { ids = { 63018, 65121 }, name = "Searing Light", desc = "A light bomb on a player that hurts nearby players. Walk away from the group." },
            { ids = { 63024, 64234 }, name = "Gravity Bomb", desc = "Pulls players in and explodes. Move away from the group." },
            { id = 62776, name = "Tympanic Tantrum", desc = "Massive raid damage every minute. Use raid cooldowns." },
        },
        hard = {
            "How to activate: kill the Heart of the Deconstructor during a Heart phase.",
            "When the Heart dies, XT-002 is healed to 100% health, gains an extra 50% health, deals 15% more damage and gains new abilities.",
            "Void Zone: if it's on you, move out of the raid and drop it away from everyone.",
            "Kill the Life Sparks that XT-002 summons.",
            "He still uses Searing Light, Gravity Bomb and Tympanic Tantrum. This is a very healing-intensive fight because of Tantrum; all players must be ready to move away from the raid with their debuffs.",
            "Raid cooldowns (Divine Guardian) and Rogue Feint help against Tantrum.",
        },
    },
    {
        name = "Assembly of Iron",
        aliases = { "Steelbreaker", "Runemaster Molgeim", "Stormcaller Brundir" },
        tldr = "Three bosses. Normal: kill Steelbreaker, then Molgeim, then Brundir. Each death heals the survivors and buffs them. Keep Brundir away from the raid (Overload), dispel Fusion Punch, avoid Rune of Death.",
        start = {
            "Three tanks: main tank on Steelbreaker, one off-tank on Molgeim (close to Steelbreaker so Rune of Power lands near him), one off-tank on Brundir far from the raid.",
            "Melee stand on Steelbreaker (High Voltage hurts everyone close to him - healable).",
        },
        general = {
            "## Normal mode - all three alive",
            "Kill order: Steelbreaker, Molgeim, then Brundir.",
            "When one boss dies, the remaining bosses are healed to 100%, gain new abilities and a stack of Supercharge. When the second dies, the last boss enters a unique phase and gets another Supercharge stack.",
            "Off-tank Brundir away from the raid because of Overload. The second off-tank handles Molgeim near Steelbreaker so Rune of Power is cast near him.",
            "Dispel Fusion Punch from Steelbreaker's tank immediately. Anyone close to Steelbreaker takes High Voltage damage (healable).",
            "Move Steelbreaker out of Rune of Power if it is cast on him; all DPS should move INTO it.",
            "## Two alive (Steelbreaker dead): Molgeim + Brundir",
            "Keep Brundir away from the raid; focus DPS on Molgeim. Dispel Shield of Runes from Molgeim, move out of Rune of Death, heal raid damage from Brundir's Lightning Whirl.",
            "## One alive (Molgeim dead): Brundir",
            "Brundir now uses Lightning Tendrils: run away from the player he locks onto (he switches targets a few times in the air). Run away when he casts Overload. Interrupt Chain Lightning and Lightning Whirl.",
            "If Rune of Power is cast on the boss you're attacking, position him so both melee and ranged can benefit.",
        },
        tank = {
            "Steelbreaker's tank: dispel Fusion Punch fast. Brundir's tank: keep him far away from the raid. Molgeim's tank: hold him near Steelbreaker.",
        },
        heal = { "Dispel Fusion Punch quickly, heal High Voltage, Lightning Whirl and Overload damage." },
        dps = { "Follow the kill order. Interrupt Chain Lightning and Lightning Whirl. Move into Rune of Power; leave Rune of Death." },
        abilities = {
            { ids = { 61903, 63493 }, name = "Fusion Punch", desc = "Heavy magic damage on Steelbreaker's tank. Dispel it immediately." },
            { ids = { 61890, 63498 }, name = "High Voltage", desc = "Raid damage from being near Steelbreaker (healable)." },
            { ids = { 62269, 63490 }, name = "Rune of Death", desc = "A rune on the ground that kills. Stay out." },
            { id = 61974, name = "Rune of Power", desc = "A buff zone on the ground. DPS should stand in it." },
            { ids = { 62274, 63489 }, name = "Shield of Runes", desc = "Molgeim's shield. Dispel it." },
            { ids = { 61915, 63483 }, name = "Lightning Whirl", desc = "Brundir's raid damage. Interrupt it if you can." },
            { ids = { 61869, 63481 }, name = "Overload", desc = "Brundir explodes for huge damage to anyone close. Run away." },
            { ids = { 61879, 63479 }, name = "Chain Lightning", desc = "Lightning that jumps. Interrupt it." },
            { ids = { 61887, 63486 }, name = "Lightning Tendrils", desc = "Brundir flies and chases a player. Run away from his target." },
            { id = 61920, name = "Supercharge", desc = "A buff the survivors get when a boss dies." },
        },
        hard = {
            "How to activate: kill the bosses in a different order - Molgeim, then Brundir, then Steelbreaker LAST. (The kill order decides the mode.)",
            "All three alive: same as normal mode.",
            "Two alive (Molgeim dead): Brundir gains Lightning Whirl and Steelbreaker gains Static Disruption. Position matters: ranged stand at max melee range in front of Steelbreaker with Brundir tanked right behind him - that puts ranged out of Overload range and melee in melee range so Static Disruption can't hit them. At least one player without Static Disruption must stay OUTSIDE the group to soak it (it never targets someone who already has it). High Voltage is amplified by players with Static Disruption. Melee run from Brundir on Overload; interrupt Chain Lightning and Lightning Whirl; keep dispelling Fusion Punch.",
            "One alive (Brundir dead): Steelbreaker gains Overwhelming Power on the main tank, which causes Meltdown after 35 seconds. The off-tanks must Taunt Steelbreaker so the affected tank can run away and not explode on the raid.",
            "Steelbreaker heals 20% of his health (10% with a healing debuff) every time a player dies, including tanks who die from Meltdown. Glyph of Rebirth is very powerful here to raise a tank. The last phase is a big DPS check.",
        },
    },
    {
        name = "Kologarn",
        aliases = { "Left Arm", "Right Arm" },
        tldr = "Focus the Right Arm (it respawns in 60 seconds), then switch to Kologarn while it's down. Pick up Rubble adds, free players from Stone Grip within 15 seconds, run from Focused Eyebeam, and keep someone in melee range at all times.",
        start = {
            "Main tank on Kologarn. An off-tank waits on the left side of the room for Rubble adds. Keep someone always in melee range of Kologarn's body - if nobody is engaging him in melee, he channels Petrifying Breath: heavy Nature damage plus a stacking Brittle Skin debuff (+20% damage taken) that can wipe the raid.",
        },
        general = {
            "DPS focus the Right Arm all fight to limit how often it can cast Stone Grip. When it's destroyed it deals damage to Kologarn's body equal to 15% of his max health and respawns after 60 seconds - switch to the body while it's down. The Left Arm is left to die slowly to melee cleave; only finish it off when a tank is free to grab the Rubble it drops.",
            "After an arm is destroyed, 5 Rubble adds spawn on that side. A free tank must pick them up immediately and drag them away from the raid (they cast Stone Nova) while ranged AoE them down. Try not to have both arms' Rubble out at once - it can overwhelm even a well-geared tank.",
            "The Right Arm casts Stone Grip; the Left Arm casts Shockwave (constant raid damage - keep healing through it).",
            "Tanks taunt-swap when the tank on Kologarn's body has 2 stacks of Crunch Armor from Overhead Smash - the window between 2 stacks and the swap is high damage, so watch tank health closely.",
        },
        tank = { "Taunt off each other at 2 stacks of Crunch Armor. Off-tank: pick up Rubble the moment an arm dies, and always keep someone in melee on the body." },
        heal = { "Free Stone Grip victims quickly (they take damage every second and die after 15 seconds if not freed) and heal the tank through Crunch Armor stacks." },
        dps = { "Right Arm first (it damages the body on death), then the body. Ranged AoE Rubble. Run from Focused Eyebeam." },
        abilities = {
            { ids = { 63356, 64003 }, name = "Overhead Smash", desc = "Heavy hit on the tank that applies a stack of Crunch Armor." },
            { name = "Crunch Armor", desc = "Stacking armor reduction from Overhead Smash. Taunt off at 2 stacks." },
            { ids = { 62166, 63981 }, name = "Stone Grip", desc = "The Right Arm grabs a player (1 in 10-man, 3 in 25-man), dealing damage every second. Free them with damage on the arm before 15 seconds is up, or they die." },
            { ids = { 63783, 63982 }, name = "Shockwave", desc = "The Left Arm's constant raid damage." },
            { ids = { 63346, 63976 }, name = "Focused Eyebeam", desc = "A beam on one player that deals AoE damage around them. Run away from the raid." },
            { name = "Petrifying Breath", desc = "Channeled heavy Nature damage plus a stacking Brittle Skin debuff, cast only when nobody is in melee range of Kologarn's body." },
        },
    },
    {
        name = "Auriaya",
        aliases = { "Feral Defender", "Sanctum Sentry" },
        tldr = "Pull carefully: the raid stands out of her line of sight and a Hunter Misdirects (or DK Death and Decay) to bring her in. Kill the Sanctum Sentries first, then the Feral Defender; stack in front of her for Sonic Screech.",
        start = {
            "Whole raid outside Auriaya's line of sight. A Hunter pulls with Misdirection (or a Death Knight with Death and Decay) so only tanks get hit by the Sentries' Savage Pounce.",
            "Fear protection helps: Tremor Totem, Fear Ward, and Shadow resistance (Prayer of Shadow Protection / Shadow Resistance Aura).",
        },
        general = {
            "Kill the Sanctum Sentries first once Auriaya reaches the raid.",
            "Everyone stands IN FRONT of Auriaya to split the damage of Sonic Screech.",
            "Terrifying Screech fears the raid and is immediately followed by Sentinel Blast - someone needs fear removed (Fear Ward, Tremor Totem, or a dispel) in time to interrupt it, since it stacks a Shadow-damage-taken vulnerability that gets dangerous fast if it goes through.",
            "DPS focus the Feral Defender when Auriaya summons it. Casters stop casting while it is casting Feral Rush.",
            "When a Feral Defender dies it leaves a Seeping Feral Essence void zone and revives in about 30 seconds. Try not to run through the void zone during Terrifying Screech. You can also LoS the dead defender so it can't Feral Pounce when it revives.",
            "AoE the Swarming Guardians (they have very little health).",
        },
        tank = { "Tanks take the Sentries and Auriaya. Only tanks should be hit by Savage Pounce." },
        heal = { "Heal the raid through Sonic Screech and keep tanks up during the fear." },
        dps = { "Sentries first, then the Feral Defender. Someone must be free of the fear to interrupt Sentinel Blast; stop casting for Feral Rush." },
        abilities = {
            { ids = { 64688, 64422 }, name = "Sonic Screech", desc = "Damage in front of Auriaya. Stack up in front to split it." },
            { id = 64386, name = "Terrifying Screech", desc = "Fears the raid. Group back up afterwards." },
            { ids = { 64389, 64678 }, name = "Sentinel Blast", desc = "Interrupt it." },
            { ids = { 64374, 64666 }, name = "Savage Pounce", desc = "The Sentries' pounce. Only tanks should get hit." },
            { ids = { 64478, 64674 }, name = "Feral Rush", desc = "Feral Defender's rush. Casters stop casting." },
            { ids = { 64457, 64458 }, name = "Seeping Feral Essence", desc = "A void zone left by a dead Feral Defender. Avoid it." },
        },
    },
    {
        name = "Hodir",
        tldr = "Free the NPC helpers from the ice first (Mages first). Keep moving to avoid Biting Cold stacks, stand at the edge of falling Icicles and on the Snowdrift when Flash Freeze comes. Use the helpers' buffs.",
        start = {
            "Free the NPCs frozen in ice at the start: FREE THE MAGES FIRST - they cast Melt Ice to free the others.",
            "Bring a Frost-resistant tank if possible (Frozen Blows).",
        },
        general = {
            "Avoid high stacks of Biting Cold by moving around. Dispel players with Freeze. Healers watch out for raid damage from Frozen Blows.",
            "Avoid the Icicles that fall from the sky - stand as close to their edge as you can.",
            "When Hodir casts Flash Freeze, the area where Icicles fell turns into a Snowdrift: STAND ON THE SNOWDRIFT to avoid being frozen.",
            "Free anyone hit by Flash Freeze (including Mage NPCs). The freed Mages help free the other NPCs.",
            "All DPS stand in the Starlight from the Druid NPCs. Casters stand near the Mage NPCs' Toasty Fire, which also removes Biting Cold.",
            "The Shaman NPCs cast Storm Power on random players: line up your cooldowns with it.",
        },
        tank = { "Keep Hodir away from the raid. A Frost-resistant tank handles Frozen Blows." },
        heal = { "Heal Frozen Blows raid damage, dispel Freeze (Priests can Mass Dispel), and free frozen players." },
        dps = { "Stay in Starlight; move to Toasty Fire to remove Biting Cold. Use cooldowns with Storm Power." },
        abilities = {
            { ids = { 62038, 62188 }, name = "Biting Cold", desc = "A stacking damage debuff when you stand still. Keep moving or stand in Toasty Fire." },
            { id = 61968, name = "Flash Freeze", desc = "Freezes players not standing on a Snowdrift." },
            { id = 62469, name = "Freeze", desc = "A freeze debuff. Dispel it." },
            { ids = { 62478, 63512 }, name = "Frozen Blows", desc = "Raid damage from Hodir. Watch your health." },
            { id = 62821, name = "Toasty Fire", desc = "A fire from the Mage NPCs that removes Biting Cold." },
            { id = 62807, name = "Starlight", desc = "A damage buff from the Druid NPCs." },
            { id = 64540, name = "Melt Ice", desc = "The Mage NPCs' spell to free frozen allies." },
        },
        hard = {
            "How to activate: kill Hodir in under 2 minutes.",
            "Everything is the same as normal mode, but the time limit turns it into a big DPS check. Using the helpers' buffs (Starlight, Storm Power, Toasty Fire) becomes much more important to reach the DPS you need.",
            "Free the Mage NPCs immediately and keep the Druids' Starlight and Shaman buffs up on all DPS.",
        },
    },
    {
        name = "Thorim",
        tldr = "Phase 1: split into an arena group and a hallway group. Arena kills adds; hallway runs the gauntlet to reach Thorim. Phase 2: spread for Chain Lightning, don't stand between Thorim and the charged Pylon, taunt-swap Unbalancing Strike. Reach Thorim in under 3 minutes for hard mode.",
        start = {
            "Split the raid in two: an ARENA group (Dark Rune adds) and a HALLWAY group (Iron Ring Guards, Runic Colossus and Ancient Rune Giant).",
            "Decide about hard mode BEFORE the pull: to keep Sif in the fight you must reach Thorim under 3 minutes; if you don't want hard mode, wait until Sif is gone before attacking Thorim.",
        },
        general = {
            "## Phase 1 - arena group",
            "Adds: Dark Rune Warbringers, Evokers, Champions and Commoners - kill in that order. Kill Warbringers first because of Aura of Celerity. Interrupt Evokers' Runic Lightning and Runic Mending.",
            "Stay spread out to reduce Stormhammer damage. Don't stand too close to the Pylons at the edge of the room when they charge.",
            "## Phase 1 - hallway group",
            "Kill and interrupt Dark Rune Acolytes first, then the Iron Ring Guard. Heal the tank to full to remove the Impale from the Iron Ring Guard. Watch the Runic Colossus in the distance to see which side it will damage - move the Iron Ring Guard to the safe side quickly because of the stun.",
            "At the Runic Colossus, face it away from the raid to avoid Smash; it may Charge a player, so get behind it quickly in case it Smashes right after.",
            "After the Colossus: a Dark Rune Acolyte and Iron Honor Guards (face them away from the raid, kill Acolytes first). At the top of the stairs is the Ancient Rune Giant: ranged don't stand in melee (Stomp) and move away from players targeted by Rune Detonation. Avoid the big circles on the ground on the way to Thorim.",
            "Reaching Thorim starts Phase 2.",
            "## Phase 2",
            "Adds stop spawning; kill any left. Stay spread for Chain Lightning. Thorim charges a Pylon again and casts Lightning Charge towards the charged Pylon - never stand between them. Lightning Charge is also a stacking enrage buff.",
            "Tanks taunt off each other when Thorim casts Unbalancing Strike.",
            "Priests can Mind Control the Dark Rune Warbringers to give the raid Aura of Celerity.",
        },
        tank = { "Phase 2: taunt-swap on Unbalancing Strike. Hallway tank: face adds away from the raid; get the Iron Ring Guard to the safe side." },
        heal = { "Hallway: heal the tank to full to remove Impale. Phase 2: heal Chain Lightning and Lightning Charge." },
        dps = { "Arena: Warbringers first. Hallway: Acolytes then guards. Phase 2: stay spread, avoid the line between Thorim and the Pylon." },
        abilities = {
            { id = 62466, name = "Lightning Charge", desc = "A lethal line towards the charged Pylon and a stacking enrage buff. Don't stand in the line." },
            { ids = { 62131, 64390 }, name = "Chain Lightning", desc = "Lightning that jumps. Stay spread out." },
            { id = 62130, name = "Unbalancing Strike", desc = "A heavy strike on the tank. Taunt-swap." },
            { id = 62320, name = "Aura of Celerity", desc = "Warbringers' aura that speeds up nearby enemies. Kill them first (or Mind Control one)." },
            { id = 62470, name = "Stormhammer", desc = "Thorim's phase 1 hammer on a player. Stay spread." },
        },
        hard = {
            "How to activate: reach Thorim under 3 minutes (from the start of the encounter) so Sif does not leave. If you prefer normal mode, wait until Sif has left before attacking Thorim.",
            "Phase 1 is the same as normal mode - just faster. Phase 2 is the same as normal mode, plus Sif joins.",
            "Sif cannot be targeted but casts a handful of abilities: avoid the Blizzard that moves around the room, cleanse players hit by Frost Nova, and healers watch for extra AoE from Frostbolt Volley.",
            "Frost resistance helps in phase 2 (Frost Resistance Aura/Totem).",
        },
    },
    {
        name = "Freya",
        aliases = { "Elder Brightleaf", "Elder Ironbranch", "Elder Stonebark" },
        tldr = "Freya can't be hit in phase 1: kill her waves of adds to remove her Attuned to Nature stacks, and kill Eonar's Gift at once. In phase 2 avoid Nature Bomb. Hard mode = start the fight WITHOUT killing the three Elders.",
        start = {
            "Choose hard mode first: do NOT kill any of the Elders before the fight to enable it. Each Elder adds an ability to Freya (see Hard mode).",
            "Pull Freya and stack for the first wave. Assign someone to kill Eonar's Gift immediately every time it appears.",
        },
        general = {
            "## Phase 1",
            "Freya is invulnerable. You must remove all her stacks of Attuned to Nature by killing adds to reach Phase 2.",
            "A tree called Eonar's Gift spawns randomly - KILL IT IMMEDIATELY or it heals Freya and her adds.",
            "Every minute a different wave spawns, in a random order. Killing adds removes her stacks.",
            "Wave with Detonating Lashers: untankable, they run from player to player. Stack up so you can AoE them, but don't kill all at once - they explode on death; single-target them when they are low.",
            "Wave with an Ancient Conservator: stand near the Mushrooms so you don't get silenced by Conservator's Grip. Move away from players targeted by Nature's Fury.",
            "Wave with Storm Lasher, Ancient Water Spirit and Snaplasher: interrupt Storm Lasher's Stormbolt and Lightning Lash; Ancient Water Spirit casts Tidal Wave. Snaplasher gets a stacking damage buff every time it's hit (falls off after 4 seconds without an attack): melee stop attacking on the call so it falls off. DoTs on Snaplasher don't add stacks.",
            "Ranged prioritise Storm Lasher and Ancient Water Spirit; melee prioritise Snaplasher.",
            "## Phase 2",
            "Avoid Nature Bomb and kill Eonar's Gift immediately.",
        },
        tank = { "Hold Freya and the adds; the Snaplasher should be tanked and faced away." },
        heal = { "Heal raid damage from waves and Nature Bomb; keep the tank alive." },
        dps = { "Ranged: Storm Lasher and Water Spirit. Melee: Snaplasher, then stop attacking when called. Everyone: Eonar's Gift first." },
        abilities = {
            { id = 62519, name = "Attuned to Nature", desc = "Freya's stacking shield in phase 1. Kill adds to remove stacks." },
            { ids = { 62589, 63571 }, name = "Nature's Fury", desc = "A marked player explodes. Move away from that player." },
            { id = 62532, name = "Conservator's Grip", desc = "Silences you unless you stand near a Mushroom." },
            { ids = { 64587, 64650 }, name = "Nature Bomb", desc = "Bombs on the ground in phase 2. Move away from them." },
        },
        hard = {
            "How to activate: start the encounter WITHOUT killing any of the three Elders (Brightleaf, Ironbranch, Stonebark).",
            "Freya keeps every normal-mode ability. Each Elder alive gives her a new ability and a passive damage boost for the whole fight.",
            "Elder Brightleaf: Unstable Energy (big yellow beams of light - move out of them) and Brightleaf's Essence.",
            "Elder Ironbranch: Iron Roots (root a player; kill the roots to free them, or remove movement-impairing effects - Hand of Freedom works) and Ironbranch's Essence.",
            "Elder Stonebark: Ground Tremor (casters must stop casting or they will be interrupted) and Stonebark's Essence.",
        },
    },
    {
        name = "Mimiron",
        aliases = { "Leviathan Mk II", "VX-001", "Aerial Command Unit" },
        tldr = "Four phases: Leviathan Mk II (dodge mines, melee run from Shock Blast), VX-001 (avoid Rapid Burst, Rocket Strike kills), Aerial Command Unit (ranged tank it, drop it with Magnetic Core), then all three together within 10 seconds. Hard mode: press the Red Button first.",
        start = {
            "Normal mode: start the fight normally. Hard mode: someone sneaks to the Red Button at the back of the room and presses it first (see Hard mode).",
            "Use Bloodlust in phase 2 (very healing-intensive). Shamans/Paladins: Fire Resistance Totem/Aura help in phases 1 and 2.",
        },
        general = {
            "## Phase 1 - Leviathan Mk II",
            "Avoid Proximity Mines. Big heals and cooldowns on the tank for Plasma Blast.",
            "ALL melee run out when Leviathan Mk II casts Shock Blast. Find a gap between the mines ahead of time so you can run straight back.",
            "Ranged DPS and healers stay spread to handle Napalm Shell damage.",
            "## Phase 2 - VX-001",
            "Heat Wave: raid-wide damage. Rapid Burst: damage in a line - melee can stay behind the boss when he turns. Rocket Strike kills anyone it hits - avoid it. Avoid P3Wx2 Laser Barrage; you can avoid it entirely if you end the phase fast.",
            "## Phase 3 - Aerial Command Unit",
            "A Ranged DPS tanks the Aerial Command Unit (it floats out of melee range). Healers watch Plasma Ball on that player.",
            "Focus Assault Bots when they spawn and loot the Magnetic Core. Use the Magnetic Core under the Aerial Command Unit to bring it down; it takes 50% more damage then - burn it. Ranged kill Bomb Bots before they reach their target. Melee can kill Junk Bots when nothing else is up.",
            "## Phase 4 - all three combined",
            "Leviathan Mk II, VX-001 and the Aerial Command Unit all fight at once with separate health pools. You must kill all of them within 10 SECONDS of each other.",
            "Leviathan Mk II only uses Proximity Mines and Shock Blast. VX-001 uses Rocket Strike, P3Wx2 Laser Barrage and a new Hand Pulse (works like Rapid Burst). The Aerial Command Unit only uses Plasma Ball.",
        },
        tank = { "Tank Leviathan Mk II on the outer edge; big cooldowns for Plasma Blast." },
        heal = { "Phase 2 needs the most healing. In phase 3 watch the ranged tank taking Plasma Ball." },
        dps = { "Phase 1: dodge mines and melee run for Shock Blast. Phase 3: kill Assault Bots; use the core on the Aerial Command Unit and kill it. Phase 4: match health so all die within 10 seconds." },
        abilities = {
            { id = 63027, name = "Proximity Mine", desc = "Mines on the ground in phase 1. Avoid touching them." },
            { ids = { 62997, 64529 }, name = "Plasma Blast", desc = "Heavy damage on the tank. Use cooldowns." },
            { id = 63631, name = "Shock Blast", desc = "A shockwave that hits melee. Melee run out." },
            { ids = { 63666, 65026 }, name = "Napalm Shell", desc = "Fire on ranged players; stay spread." },
            { id = 63677, name = "Heat Wave", desc = "VX-001's raid-wide damage." },
            { id = 63382, name = "Rapid Burst", desc = "Rapid damage in a line in front of VX-001." },
            { id = 63041, name = "Rocket Strike", desc = "A rocket that kills whoever it lands on. Move away." },
            { id = 63274, name = "P3Wx2 Laser Barrage", desc = "A sweeping laser. Avoid it." },
            { ids = { 63689, 64535 }, name = "Plasma Ball", desc = "Damage on the ranged tank of the Aerial Command Unit." },
            { id = 64444, name = "Magnetic Core", desc = "Dropped by Assault Bots; used to pull the Aerial Command Unit down." },
            { id = 64348, name = "Hand Pulse", desc = "VX-001's phase 4 ability, like Rapid Burst." },
        },
        hard = {
            "How to activate: someone sneaks behind Mimiron and presses the Red Button at the back of the room to start the fight.",
            "Mimiron gains 25% health and 25% damage, and every phase keeps its normal abilities and gains ONE extra ability. Flames spawn on random players and follow the player they are closest to.",
            "During EVERY transition phase, the whole raid groups up wherever there are the most Flames, as close to them as possible, to contain them in one area.",
            "Phase 1: Tank Leviathan Mk II on the outer edge and move him whenever he casts Shock Blast so you avoid the Proximity Mines. New ability: Flame Suppressant (about halfway through the phase).",
            "Phase 2: VX-001 spawns a Frost Bomb at the start and about every minute after. The first Frost Bomb should extinguish most of the area where you were dropping Flames. Watch for extra Frost Bombs and run away before they explode.",
            "Phase 3: Emergency Fire Bots spawn alongside the normal Bots (Deafening Siren aura and Water Spray). Kill them as quickly as possible. Save the Magnetic Core from the Assault Bots so you can use two back to back - a good time for Bloodlust. Kill all remaining adds during the transition.",
            "Phase 4: Frost Bomb is the extra ability again. Plan your movement ahead because of Flames and Frost Bomb on top of normal mode mechanics.",
        },
    },
    {
        name = "General Vezax",
        aliases = { "Saronite Animus" },
        tldr = "Interrupt Searing Flames, avoid Shadow Crash, spread for Mark of the Faceless, and use Saronite Vapors carefully for mana. Hard mode: don't kill any Saronite Vapors, so all 8 merge into the Saronite Animus.",
        start = {
            "Tank Vezax facing away from the raid. Shadow resistance (Prayer of Shadow Protection / Shadow Resistance Aura) helps.",
            "Casters plan to stand in Shadow Crash's energy field afterwards; everyone spreads before the Mark of the Faceless.",
        },
        general = {
            "Interrupt Searing Flames. Avoid Shadow Crash. Casters stand IN the energy field left by Shadow Crash. (A Discipline Priest's Power Word: Shield isn't reduced in the field because it is a shield.)",
            "Ranged stay spread for Mark of the Faceless (it also heals Vezax if it hits people).",
            "When Vezax casts Surge of Darkness you can kite him or use raid cooldowns and heal through it.",
            "Kill the Saronite Vapors and stand in the green puddle to regain mana if you need it - but don't stay long, it drains your life.",
        },
        tank = { "Face him away, use a cooldown for Surge of Darkness or kite him." },
        heal = { "Watch mana; Saronite Vapors puddles restore mana in normal mode." },
        dps = { "Interrupt Searing Flames. Casters use the Shadow Crash field; stay spread for Mark of the Faceless." },
        abilities = {
            { id = 62692, name = "Aura of Despair", desc = "A passive aura on Vezax that stops normal mana regeneration - the reason Saronite Vapors matter." },
            { id = 62661, name = "Searing Flames", desc = "A big cast that must be interrupted." },
            { id = 62660, name = "Shadow Crash", desc = "Shadow on a player's position. Avoid it; casters use the leftover field." },
            { id = 63276, name = "Mark of the Faceless", desc = "A mark that damages nearby players and heals Vezax. Stay spread." },
            { id = 62662, name = "Surge of Darkness", desc = "Massive damage on the tank. Kite or use cooldowns." },
            { id = 63322, name = "Saronite Vapors", desc = "A green cloud that restores mana when you stand in it (drains health if you stay too long)." },
            { id = 63420, name = "Profound Darkness", desc = "The Saronite Animus's stacking shadow damage in hard mode." },
            { id = 63364, name = "Saronite Barrier", desc = "Vezax's shield while the Animus lives in hard mode." },
        },
        hard = {
            "How to activate: do NOT kill any Saronite Vapors for the whole fight. One spawns roughly every 30 seconds; once the 8th has spawned with all of them still alive, they merge into the Saronite Animus. Watch your AoE - accidentally killing one resets your attempt at hard mode.",
            "Vezax gains Saronite Barrier (99% damage reduction) while the Animus lives, so all DPS must burn the Animus down. It continuously casts Profound Darkness on the raid, so the longer this phase lasts, the harder it is on healers - use raid cooldowns and Bloodlust here.",
            "Vezax keeps casting Shadow Crash, Searing Flames and Surge of Darkness the whole time the Animus is up - interrupts and positioning still matter, they don't pause for the add.",
            "After the Animus dies, Vezax loses Saronite Barrier and you finish him off. Shadow Crash stays dangerous because Profound Darkness stacks are still on the raid.",
            "Healers must manage mana carefully the entire fight, since none of it can come from Saronite Vapors on hard mode - Dark Runes/Demonic Runes and mana-efficient healing matter more than usual.",
        },
    },
    {
        name = "Yogg-Saron",
        aliases = { "Sara", "Brain of Yogg-Saron", "Guardian of Yogg-Saron", "Immortal Guardian" },
        tldr = "Three phases and Sanity: keep your Sanity up. P1 kill Guardians near Sara; P2 kill tentacles and enter the Brain room; P3 kill Yogg while Guardians are brought to 1% health. Hard mode = fewer Keepers helping.",
        start = {
            "Every player has a Sanity buff: if you run out you are Insane and must be killed. Look for Sanity Wells (Freya's help) to restore it.",
            "The four Keepers (Freya, Hodir, Mimiron, Thorim) will help you in the fight unless you deactivated them before starting (see Hard mode).",
            "Assign portal teams in phase 2 (usually melee DPS and 1 healer).",
        },
        general = {
            "## Phase 1",
            "Avoid the Ominous Cloud. Kill Guardians of Yogg-Saron near Sara so they damage her with Shadow Nova. Interrupt Dark Volley from the Guardians.",
            "Phase 2 starts when Sara is hit by 8 Shadow Novas.",
            "## Phase 2",
            "Don't lose all of your Sanity. Ranged DPS focus Crusher Tentacles; melee DPS focus Corruptor Tentacles. One tank can take the Crusher Tentacles for Diminish Power but beware Focused Anger.",
            "Dispel all debuffs the Corruptor Tentacles apply to the raid. Kill Constrictor Tentacles when they grab someone.",
            "Brain Link: if you get it, get close to the player you're linked with (a yellow beam means you're safe). Avoid Death Ray.",
            "When the 10 Portals spawn, assigned players with high Sanity enter (one player per portal). Inside, you're in a circular room: kill all the Influence Tentacles (disguised as neutral mobs). Look away from the Laughing Skull to avoid Lunatic Gaze.",
            "When all Influence Tentacles are dead, the room to the Brain of Yogg-Saron opens. DPS the Brain, but take a Portal out BEFORE Induce Madness finishes casting.",
            "Phase 3 starts when the Brain reaches 30%: make sure no Crusher Tentacles are alive.",
            "## Phase 3",
            "Turn away from Yogg-Saron if you're targeted by Lunatic Gaze. Bring Immortal Guardians down to 1% health as fast as possible - Thorim finishes them with Titanic Storm. Watch for Empowered Guardians.",
            "If an Immortal Guardian is targeted by Shadow Beacon, move it away from other Guardians and Yogg-Saron before it goes off. It then gains Empowering Shadows and heals itself and everything around it.",
        },
        tank = { "Phase 1 and 3: hold Guardians away from the raid. Phase 2: one tank can hold Crusher Tentacles." },
        heal = { "Keep Sanity healers ready, dispel Corruptor debuffs, and heal through tank damage." },
        dps = { "Phase 1: Guardians near Sara. Phase 2: ranged on Crushers, melee on Corruptors; portal teams kill Influence Tentacles then the Brain. Phase 3: Yogg-Saron, keep Guardians at 1%." },
        abilities = {
            { id = 63050, name = "Sanity", desc = "Your mental health. Reaching 0 makes you Insane." },
            { id = 62714, name = "Shadow Nova", desc = "Guardian deaths near Sara cause this on her - 8 hits start phase 2." },
            { id = 63038, name = "Dark Volley", desc = "Guardians' cast. Interrupt it." },
            { id = 64148, name = "Diminish Power", desc = "Crusher Tentacles reduce damage. One tank can hold them." },
            { id = 57689, name = "Focused Anger", desc = "Builds on a tank holding Crusher Tentacles." },
            { id = 63802, name = "Brain Link", desc = "Links two players. Get close to your partner." },
            { id = 63884, name = "Death Ray", desc = "A deadly ground effect. Avoid it." },
            { id = 64163, name = "Lunatic Gaze", desc = "A gaze effect. Look away from Yogg-Saron or the Skull." },
            { id = 64059, name = "Induce Madness", desc = "Cast in the Brain room: leave before it finishes." },
            { id = 64465, name = "Shadow Beacon", desc = "Marks an Immortal Guardian; move it away before it explodes." },
            { id = 64467, name = "Empowering Shadows", desc = "A marked Guardian heals itself and everything near it." },
            { id = 64171, name = "Titanic Storm", desc = "Thorim's help: kills Immortal Guardians at 1% health." },
            { id = 64189, name = "Deafening Roar", desc = "A 0-Keeper phase 3 ability that hits the raid." },
            { id = 64174, name = "Hodir's Protective Gaze", desc = "Hodir's help: saves a player from fatal damage." },
        },
        hard = {
            "How to activate: before the fight, choose how many Keepers (Freya, Hodir, Mimiron, Thorim) to leave active - each one you deactivate removes their help. 0 Keepers is the hardest.",
            "The Keepers give passive damage, healing and damage reduction plus an active ability: Freya's Sanity Well, Hodir's Protective Gaze (saves a player from fatal damage), Mimiron's Destabilization Matrix, and Thorim's Titanic Storm (kills Immortal Guardians at 1%).",
            "0 Keepers: Yogg-Saron gains Deafening Roar in Phase 3 and you lose all Keeper help (passive damage, healing, damage reduction). It's impossible to kill Immortal Guardians without Thorim's Titanic Storm.",
            "Phase 1 and 2 are harder because you lose utility. In phase 3 keep Immortal Guardians low on health to deal with Empowered - but don't put too many players on AoE (you still need to kill Yogg-Saron).",
            "Off-tanks alternate picking up Immortal Guardians as they spawn. Don't over-AoE Guardians already at 1% health. If Shadow Beacon empowers one and it heals to full, bring it back down with the others.",
            "Healers top off tanks before Deafening Roar. Paladins: Aura Mastery and Concentration Aura help against it.",
            "1 Keeper (keep Thorim): same as normal mode strategy plus Deafening Roar; Thorim's Titanic Storm can still kill Guardians.",
        },
    },
    {
        name = "Algalon the Observer",
        aliases = { "Living Constellation", "Collapsing Star" },
        tldr = "Kill Collapsing Stars one at a time, avoid Cosmic Smash, and when Big Bang comes ALL BUT ONE player walks over a Black Hole to be safe; one must stay behind and survive. Phase 2 at 20%.",
        start = {
            "Tank Algalon; the off-tanks stand ready to taunt at 4 stacks of Phase Punch.",
            "Choose the player who will stay behind for each Big Bang - a Shadow Priest with Dispersion is a good candidate.",
        },
        general = {
            "## Phase 1",
            "Healers watch spike damage from Quantum Strike. Off-tanks Taunt Algalon when the main tank has 4 stacks of Phase Punch (cast every 15 seconds).",
            "Sets of four Collapsing Stars appear. They lose 1% health per second and explode on death for raid damage: coordinate killing them ONE at a time (1-2 DPS assigned). A killed Collapsing Star leaves a Black Hole.",
            "Every 90 seconds Big Bang: everyone EXCEPT ONE player must walk over a Black Hole to be taken to the other realm and avoid the damage. Avoid the Dark Matter adds there. The player left behind must survive, or Algalon wipes the raid with Ascend to the Heavens.",
            "3 Cosmic Smash zones appear on the ground as red void zones: stay at least 10 yards away.",
            "Kite Living Constellations through Black Holes to kill them (they also remove the hole).",
            "## Phase 2 (starts at 20% health)",
            "Collapsing Stars and Constellations disappear; the original Black Holes vanish and four new ones spawn in set positions. Unleashed Dark Matter spawns from the Black Holes every 30 seconds: an off-tank picks them up off to the side. DPS focus Algalon and ignore the adds.",
        },
        tank = { "Taunt swap at 4 stacks of Phase Punch. Off-tank: Dark Matter in phase 2." },
        heal = { "Big Bang is a raid cooldown moment. Heal tank spikes from Quantum Strike." },
        dps = { "Kill Collapsing Stars one at a time. Kite Constellations through Black Holes. Stay 10 yards from Cosmic Smash." },
        abilities = {
            { ids = { 64395, 64592 }, name = "Quantum Strike", desc = "Heavy damage on the tank." },
            { id = 64412, name = "Phase Punch", desc = "A stacking debuff on the tank; swap at 4 stacks." },
            { ids = { 64443, 64584 }, name = "Big Bang", desc = "Massive raid damage every 90 seconds. Only a Black Hole saves you (immunities don't work)." },
            { ids = { 62301, 64598 }, name = "Cosmic Smash", desc = "Red void zones - stay 10 yards away." },
            { id = 64487, name = "Ascend to the Heavens", desc = "Wipes the raid if everyone leaves the realm during Big Bang." },
        },
        hard = {
            "Algalon has no normal mode - this fight is only available as the optional hard-mode encounter after clearing the Keepers' sigil quests.",
            "Immune effects such as Ice Block and Divine Shield do NOT work on Big Bang. Death Knights (Death Grip) and Balance Druids (Typhoon) can displace Living Constellations into Black Holes.",
        },
    },
}, "Syndicate Guild (Ulduar page: Flame Leviathan and Ignis calls) and wowtbc.gg (normal and hard mode for every boss)")
